spring.application.name=eindopdracht

POSTGRESQL_DATABASENAME = eindopdracht
POSTGRESQL_USERNAME = postgres
POSTGRESQL_PASSWORD = password

spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRESQL_DATABASENAME}
spring.datasource.username=postgres
spring.datasource.password=password

# Jpa instellingen
spring.jpa.show-sql=true

# forces to generate the data structures
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create

# database initialization with data.sql after hibernate
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# client-id = eindopdracht
# issuer-uri = http://localhost:9090/realms/eindopdracht
# client-secret = H6DVH6h8B6YKEBdnfIIxjstnf5pYL2HR
# audience = account
# spring.security.oauth2.resourceserver.jwt.issuer-uri= ${issuer-uri}
# spring.security.oauth2.resourceserver.jwt.audiences= ${audience}